import { FrameTheme, PhotoFilter, StickerPlacement } from "../types/photobooth";

export const FRAME_THEMES: FrameTheme[] = [
  {
    id: "transium-blue",
    name: "Transium Blue",
    bgClass: "bg-[#3673FD]",
    bgColor: "#3673FD",
    textColor: "#FFFFFF",
    subtextColor: "#DBEAFE",
  },
  {
    id: "vintage-crimson",
    name: "Crimson Red",
    bgClass: "bg-[#9A1B1B]",
    bgColor: "#9A1B1B",
    textColor: "#FFFFFF",
    subtextColor: "#FECACA",
  },
  {
    id: "cotton-candy-pink",
    name: "Pastel Pink",
    bgClass: "bg-[#FBCFE8]",
    bgColor: "#FBCFE8",
    textColor: "#831843",
    subtextColor: "#9D174D",
  },
  {
    id: "soft-sky",
    name: "Baby Blue",
    bgClass: "bg-[#BFDBFE]",
    bgColor: "#BFDBFE",
    textColor: "#1E3A8A",
    subtextColor: "#1D4ED8",
  },
  {
    id: "butter-cream",
    name: "Warm Cream",
    bgClass: "bg-[#FEF3C7]",
    bgColor: "#FEF3C7",
    textColor: "#78350F",
    subtextColor: "#92400E",
  },
  {
    id: "classic-white",
    name: "Pure White",
    bgClass: "bg-[#FFFFFF]",
    bgColor: "#FFFFFF",
    textColor: "#1E293B",
    subtextColor: "#64748B",
    borderColor: "#E2E8F0",
  },
  {
    id: "midnight-black",
    name: "Jet Black",
    bgClass: "bg-[#18181B]",
    bgColor: "#18181B",
    textColor: "#FFFFFF",
    subtextColor: "#A1A1AA",
  },
  {
    id: "matcha-sage",
    name: "Matcha Sage",
    bgClass: "bg-[#D1E7DD]",
    bgColor: "#D1E7DD",
    textColor: "#14532D",
    subtextColor: "#15803D",
  },
];

export const PHOTO_FILTERS: PhotoFilter[] = [
  {
    id: "normal",
    name: "Original",
    cssFilter: "none",
    canvasFilter: "none",
    description: "Clean and natural colors",
  },
  {
    id: "warm-vintage",
    name: "Warm 90s",
    cssFilter: "sepia(0.2) saturate(1.25) contrast(1.05) brightness(1.03)",
    canvasFilter: "sepia(20%) saturate(125%) contrast(105%) brightness(103%)",
    description: "Golden hour nostalgia tone",
  },
  {
    id: "black-white",
    name: "B & W",
    cssFilter: "grayscale(1) contrast(1.2) brightness(1.05)",
    canvasFilter: "grayscale(100%) contrast(120%) brightness(105%)",
    description: "Classic high contrast monochrome",
  },
  {
    id: "soft-glow",
    name: "Soft Glow",
    cssFilter: "brightness(1.08) contrast(0.95) saturate(1.15)",
    canvasFilter: "brightness(108%) contrast(95%) saturate(115%)",
    description: "Smooth luminous skin tone",
  },
  {
    id: "cinematic",
    name: "Film Pop",
    cssFilter: "contrast(1.15) saturate(1.35) hue-rotate(-5deg)",
    canvasFilter: "contrast(115%) saturate(135%) hue-rotate(-5deg)",
    description: "Vivid, rich dynamic range",
  },
  {
    id: "pastel-dream",
    name: "Pastel",
    cssFilter: "brightness(1.12) saturate(0.88) contrast(1.02) sepia(0.1)",
    canvasFilter: "brightness(112%) saturate(88%) contrast(102%) sepia(10%)",
    description: "Dreamy soft aesthetic",
  },
];

// Default 4-cut photobooth sticker placement
// Uses ALL provided assets scattered around the 4 photos and margins
export const DEFAULT_STICKER_PRESETS: Record<string, { name: string; stickers: StickerPlacement[] }> = {
  default: {
    name: "Full Transium Scatter",
    stickers: [
      // 1. Top Section - Near Header / Photo 1
      {
        id: "confetti-top-left",
        src: "/assets/confetti-1.png",
        alt: "Confetti",
        xPercent: 12,
        yPercent: 6,
        widthPercent: 15,
        rotationDeg: -18,
        zIndex: 10,
      },
      {
        id: "star-top-right",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 88,
        yPercent: 5.5,
        widthPercent: 13,
        rotationDeg: 16,
        zIndex: 10,
      },
      {
        id: "dash-top-left",
        src: "/assets/dash-lines.png",
        alt: "Sparkle lines",
        xPercent: 24,
        yPercent: 11,
        widthPercent: 12,
        rotationDeg: -22,
        zIndex: 10,
      },

      // 2. Around Photo 1 & 2 Border
      {
        id: "badge-1",
        src: "/assets/badge-1.png",
        alt: "Cafe Stamp",
        xPercent: 86,
        yPercent: 17,
        widthPercent: 25,
        rotationDeg: 12,
        zIndex: 20,
      },
      {
        id: "star-p1-left",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 10,
        yPercent: 23,
        widthPercent: 12,
        rotationDeg: -14,
        zIndex: 15,
      },
      {
        id: "badge-2",
        src: "/assets/badge-2.png",
        alt: "Ice Cream Stamp",
        xPercent: 14,
        yPercent: 33,
        widthPercent: 24,
        rotationDeg: -10,
        zIndex: 20,
      },
      {
        id: "confetti-p2-right",
        src: "/assets/confetti-2.png",
        alt: "Confetti",
        xPercent: 88,
        yPercent: 37,
        widthPercent: 14,
        rotationDeg: 25,
        zIndex: 10,
      },

      // 3. Around Photo 2 & 3 Border
      {
        id: "transium-bus-logo",
        src: "/assets/transium-logo.png",
        alt: "Transium Bus Icon",
        xPercent: 85,
        yPercent: 53,
        widthPercent: 26,
        rotationDeg: -12,
        zIndex: 25,
      },
      {
        id: "dash-mid-left",
        src: "/assets/dash-lines.png",
        alt: "Dash lines",
        xPercent: 13,
        yPercent: 47,
        widthPercent: 11,
        rotationDeg: 45,
        zIndex: 10,
      },
      {
        id: "badge-3",
        src: "/assets/badge-3.png",
        alt: "Sunset Gazebo Stamp",
        xPercent: 14,
        yPercent: 57,
        widthPercent: 25,
        rotationDeg: 8,
        zIndex: 20,
      },
      {
        id: "star-mid-right",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 89,
        yPercent: 67,
        widthPercent: 13,
        rotationDeg: 28,
        zIndex: 15,
      },

      // 4. Around Photo 3 & 4 Border
      {
        id: "badge-4",
        src: "/assets/badge-4.png",
        alt: "Kite Festival Stamp",
        xPercent: 87,
        yPercent: 76,
        widthPercent: 24,
        rotationDeg: -8,
        zIndex: 20,
      },
      {
        id: "confetti-p4-left",
        src: "/assets/confetti-1.png",
        alt: "Confetti",
        xPercent: 11,
        yPercent: 73,
        widthPercent: 14,
        rotationDeg: -35,
        zIndex: 10,
      },

      // 5. Bottom Section / Photo 4 Footer
      {
        id: "badge-5",
        src: "/assets/badge-5.png",
        alt: "Traditional Market Stamp",
        xPercent: 16,
        yPercent: 89,
        widthPercent: 25,
        rotationDeg: -9,
        zIndex: 20,
      },
      {
        id: "dash-bottom-right",
        src: "/assets/dash-lines.png",
        alt: "Sparkle lines",
        xPercent: 84,
        yPercent: 87,
        widthPercent: 12,
        rotationDeg: -15,
        zIndex: 15,
      },
      {
        id: "confetti-bottom-right",
        src: "/assets/confetti-2.png",
        alt: "Confetti",
        xPercent: 88,
        yPercent: 95,
        widthPercent: 13,
        rotationDeg: 15,
        zIndex: 10,
      },
      {
        id: "star-bottom-center",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 48,
        yPercent: 96.5,
        widthPercent: 9,
        rotationDeg: 12,
        zIndex: 12,
      },
    ],
  },
  stamps: {
    name: "Stamps Focus",
    stickers: [
      {
        id: "badge-1",
        src: "/assets/badge-1.png",
        alt: "Cafe Stamp",
        xPercent: 85,
        yPercent: 15,
        widthPercent: 26,
        rotationDeg: 10,
        zIndex: 20,
      },
      {
        id: "badge-2",
        src: "/assets/badge-2.png",
        alt: "Ice Cream Stamp",
        xPercent: 15,
        yPercent: 35,
        widthPercent: 25,
        rotationDeg: -12,
        zIndex: 20,
      },
      {
        id: "badge-3",
        src: "/assets/badge-3.png",
        alt: "Sunset Gazebo Stamp",
        xPercent: 85,
        yPercent: 55,
        widthPercent: 25,
        rotationDeg: 8,
        zIndex: 20,
      },
      {
        id: "badge-4",
        src: "/assets/badge-4.png",
        alt: "Kite Festival Stamp",
        xPercent: 15,
        yPercent: 75,
        widthPercent: 25,
        rotationDeg: -8,
        zIndex: 20,
      },
      {
        id: "badge-5",
        src: "/assets/badge-5.png",
        alt: "Market Stamp",
        xPercent: 84,
        yPercent: 90,
        widthPercent: 25,
        rotationDeg: 12,
        zIndex: 20,
      },
      {
        id: "transium-bus-logo",
        src: "/assets/transium-logo.png",
        alt: "Bus Logo",
        xPercent: 16,
        yPercent: 92,
        widthPercent: 24,
        rotationDeg: -6,
        zIndex: 20,
      },
      {
        id: "star-1",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 88,
        yPercent: 6,
        widthPercent: 12,
        rotationDeg: 15,
        zIndex: 10,
      },
    ],
  },
  minimal: {
    name: "Minimal Chic",
    stickers: [
      {
        id: "star-top",
        src: "/assets/star.png",
        alt: "Star",
        xPercent: 86,
        yPercent: 6,
        widthPercent: 12,
        rotationDeg: 15,
        zIndex: 10,
      },
      {
        id: "transium-bus-logo",
        src: "/assets/transium-logo.png",
        alt: "Transium Bus",
        xPercent: 85,
        yPercent: 50,
        widthPercent: 24,
        rotationDeg: -10,
        zIndex: 20,
      },
      {
        id: "badge-2",
        src: "/assets/badge-2.png",
        alt: "Ice cream",
        xPercent: 15,
        yPercent: 74,
        widthPercent: 23,
        rotationDeg: -8,
        zIndex: 20,
      },
      {
        id: "confetti-bottom",
        src: "/assets/confetti-2.png",
        alt: "Confetti",
        xPercent: 85,
        yPercent: 94,
        widthPercent: 14,
        rotationDeg: 20,
        zIndex: 10,
      },
    ],
  },
};
